version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  spleeter:
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - gcp_vidby_key:/gcp
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /gcp/gcp_vidby_key.json
      WEBHOOK_HOST: http://staging.vidby.com
      SPLITTING_FREQUENCY: 10
      AUDIO_SPLIT_SERVICE_CELERY_BROKER_URL: redis://redis:6379
    depends_on:
      - redis
  celery:
    build:
      context: ..
      dockerfile: ./Dockerfile
    command: celery -A src.celery_tasks.celery worker -l INFO --pool solo
    volumes:
      - gcp_vidby_key:/gcp
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /gcp/gcp_vidby_key.json
      WEBHOOK_HOST: http://staging.vidby.com
      SPLITTING_FREQUENCY: 10
      AUDIO_SPLIT_SERVICE_CELERY_BROKER_URL: redis://redis:6379
    depends_on:
      - redis

volumes:
  gcp_vidby_key:
    external: true
